baseurl: https://serenitycode.dev
languageCode: en-us
title: SerenityCode Marek Pikuła
copyright: SerenityCode Marek Pikuła

# Theme i18n support
# Available values: ar, bn, ca, de, el, en, es, fr, hu, id, it, ja, ko, nl, pt-br, th, uk, zh-cn, zh-hk, zh-tw
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

services:
  # Change it to your Disqus shortname before using
  disqus:
    shortname: marekpikula
  # GA Tracking ID
  googleAnalytics:
    id: G-RR3MX3G9LN

pagination:
    pagerSize: 5
