social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/MarekPikula"
    params:
      icon: "brand-github"
  - identifier: "linkedin"
    name: "LinkedIn"
    url: "https://www.linkedin.com/in/marek-pikula/"
    params:
      icon: "brand-linkedin"

main:
  - identifier: "kofi"
    name: "Buy Me a Ko-fi"
    url: "https://ko-fi.com/marekpikula"
    weight: -100
    params:
      icon: "coffee"
      newTab: true
