social:
  - identifier: "github"
    name: "GitHub"
    url: "https://github.com/MarekPikula"
    params:
      icon: "brand-github"
  - identifier: "linkedin"
    name: "LinkedIn"
    url: "https://www.linkedin.com/in/marek-pikula/"
    params:
      icon: "brand-linkedin"
  - identifier: "medium"
    name: "Medium"
    url: "https://medium.com/@MarekPikula"
    params:
      icon: "brand-medium"
