repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: resources/
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://gitlab.com/bmares/check-json5
    rev: "v1.0.0"
    hooks:
      - id: check-json5
  - repo: local
    hooks:
    - id: hugo
      name: Regenerate Hugo resources
      description: This hook regenerates Hugo resources to be commited to repo.
      entry: hugo --gc --minify
      pass_filenames: false
      always_run: true
      language: system
  - repo: local
    hooks:
    - id: optipng
      name: Optimize PNG files
      description: This hook tries to optimize PNG files.
      entry: optipng
      files: \.png$
      language: system
