name: Deploy Hugo site to Pages

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Checkout LFS objects
        run: git lfs checkout

      # Hugo setup
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"
          extended: true

      # pre-commit setup
      - name: Setup Python for pre-commit
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip

      - name: Cache pre-commit environments
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit/
          key: pre-commit-4|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Perform pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: Apply pre-commit-ci-lite auto-fixes
        uses: pre-commit-ci/lite-action@v1.1.0
        if: always()

      # Pages setup
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Build and upload
      - name: Build
        run: hugo --minify --gc --baseURL ${{ steps.pages.outputs.base_url }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    if: github.event_name == 'push'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
